import Head from "next/head";
import { db } from "../libs/firebase";
import { useEffect } from "react";
import { collection, addDoc, getDocs } from "firebase/firestore";

export default function Home() {
  useEffect(() => {
    test();
  }, []);

  const test = async () => {
    const docRef = await addDoc(collection(db, "users"), {
      first: "Adaaaaaa",
      last: "Lovelace",
      born: 1815,
    });
    console.log("Document written with ID: ", docRef.id);

    const querySnapshot = await getDocs(collection(db, "users"));
    querySnapshot.forEach((doc) => {
      // doc.data() is never undefined for query doc snapshots
      console.log(doc.id, " => ", doc.data());
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/to-do-list.png" />
      </Head>
      <div className="h-screen flex flex-col items-center justify-center font-bold">
        Hello world
      </div>
    </>
  );
}
